POST http://localhost:8080/api/v1.0/register
Content-Type: application/json

{
  "name": "Anvar Alekperov",
  "email": "azgangsta@gmail.com",
  "password": "123456"
}
###

POST http://localhost:8080/api/v1.0/login
Content-Type: application/json

{
  "email": "azgangsta@gmail.com",
  "password": "123456"
}

###
GET http://localhost:8080/api/v1.0/profile

###

GET http://localhost:8080/api/v1.0/is-authenticated

###

POST http://localhost:8080/api/v1.0/send-reset-otp?
    email=azgangsta@gmail.com

###

POST http://localhost:8080/api/v1.0/reset-password
Content-Type: application/json

{
  "email": "azgangsta@gmail.com",
  "otp": "737709",
  "newPassword": "654321"
}
###
POST http://localhost:8080/api/v1.0/send-otp

###

POST http://localhost:8080/api/v1.0/verify-otp
Content-Type: application/json

{
  "otp" : "789888"
}

###

